"""
CyberKey RSSI Analyzer

Purpose:
- Read the log file generated by cyberkey_scan.py
- Show statistics per discovered device to help with calibration.
"""

import csv
from collections import defaultdict
from pathlib import Path

LOG_FILE = Path(__file__).parent.parent / "logs" / "cyberkey_rssi_log.csv"

def analyze():
    if not LOG_FILE.exists():
        print(f"No log file found at: {LOG_FILE.resolve()}")
        print("Run cyberkey_scan.py first to collect data.")
        return

    data = defaultdict(list)
    last_seen = {}

    with open(LOG_FILE, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            mac = row.get("address", "Unknown MAC")
            name = row.get("name", "Unknown Name")
            try:
                rssi = int(row.get("rssi", 0))
            except ValueError:
                continue

            timestamp = row.get("timestamp", "Unknown Time")

            key = f"{name} ({mac})"
            data[key].append(rssi)
            last_seen[key] = timestamp

    print("==================================================")
    print("CyberKey RSSI Analysis")
    print("==================================================")

    if not data:
        print("No valid data found in the log file.")
        return

    for key, rssi_list in data.items():
        count = len(rssi_list)
        avg = sum(rssi_list) / count
        minimum = min(rssi_list)
        maximum = max(rssi_list)

        print(f"Device: {key}")
        print(f"  Number of readings: {count}")
        print(f"  RSSI Minimum      : {minimum} dBm")
        print(f"  RSSI Maximum      : {maximum} dBm")
        print(f"  RSSI Average      : {avg:.1f} dBm")
        print(f"  Last seen         : {last_seen[key]}")
        print("-" * 50)

if __name__ == "__main__":
    analyze()
